### ISSUE TITLE
License file missing from PyPI tarball

### ISSUE THREAD

**Issue by scopatz** [anki-code/xontrib-pipeliner#2]
probably needs to be added in setup.py

**Comment by anki-code** [comment]
Hi @scopatz! Glad to meet you here :) I thought today that pipeliner could be the basic xonsh feature and [Python code should be freed from the string](https://github.com/anki-code/xontrib-pipeliner#escape-from-the-string) and look i.e.  `ls | @@(line + 'is here')` :) But I haven't enough experience to do it in xonsh )

By the issue I see the license in `setup.py`: `license='BSD',` and appropriate license in [PyPi package](https://pypi.org/project/xontrib-pipeliner/):

![image](https://user-images.githubusercontent.com/1708680/92796514-ed107700-f3b9-11ea-813c-95fe8d6b8279.png)

What did you mean?

**Comment by scopatz** [comment]
Ahh yeah, I mean the actual `LICENSE` file itself is not present in the pypi package

**Comment by anki-code** [comment]
The file is there :) Look closer :)

**Comment by anki-code** [comment]
May be you mean `MANIFEST.in` with `include LICENSE`. Added!

**Comment by scopatz** [comment]
Yeah, that is what I mean, thanks!
